/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ApiPublicHooksIngestRouteImport } from './routes/api/public/hooks/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestRoute = ApiPublicHooksIngestRouteImport.update({
  id: '/api/public/hooks/ingest',
  path: '/api/public/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/radar' | '/api/public/hooks/ingest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/radar' | '/api/public/hooks/ingest'
  id: '__root__' | '/' | '/radar' | '/api/public/hooks/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RadarRoute: typeof RadarRoute
  ApiPublicHooksIngestRoute: typeof ApiPublicHooksIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest': {
      id: '/api/public/hooks/ingest'
      path: '/api/public/hooks/ingest'
      fullPath: '/api/public/hooks/ingest'
      preLoaderRoute: typeof ApiPublicHooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RadarRoute: RadarRoute,
  ApiPublicHooksIngestRoute: ApiPublicHooksIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
