/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrosswalkRouteImport } from './routes/crosswalk'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as StoreRouteImport } from './routes/store'
import { Route as BriefSlugRouteImport } from './routes/brief.$slug'
import { Route as ApiPublicHooksIngestRouteImport } from './routes/api/public/hooks/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosswalkRoute = CrosswalkRouteImport.update({
  id: '/crosswalk',
  path: '/crosswalk',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefSlugRoute = BriefSlugRouteImport.update({
  id: '/brief/$slug',
  path: '/brief/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestRoute = ApiPublicHooksIngestRouteImport.update({
  id: '/api/public/hooks/ingest',
  path: '/api/public/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crosswalk': typeof CrosswalkRoute
  '/graph': typeof GraphRoute
  '/radar': typeof RadarRoute
  '/store': typeof StoreRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crosswalk': typeof CrosswalkRoute
  '/graph': typeof GraphRoute
  '/radar': typeof RadarRoute
  '/store': typeof StoreRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crosswalk': typeof CrosswalkRoute
  '/graph': typeof GraphRoute
  '/radar': typeof RadarRoute
  '/store': typeof StoreRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crosswalk'
    | '/graph'
    | '/radar'
    | '/store'
    | '/brief/$slug'
    | '/api/public/hooks/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crosswalk'
    | '/graph'
    | '/radar'
    | '/store'
    | '/brief/$slug'
    | '/api/public/hooks/ingest'
  id:
    | '__root__'
    | '/'
    | '/crosswalk'
    | '/graph'
    | '/radar'
    | '/store'
    | '/brief/$slug'
    | '/api/public/hooks/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrosswalkRoute: typeof CrosswalkRoute
  GraphRoute: typeof GraphRoute
  RadarRoute: typeof RadarRoute
  StoreRoute: typeof StoreRoute
  BriefSlugRoute: typeof BriefSlugRoute
  ApiPublicHooksIngestRoute: typeof ApiPublicHooksIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crosswalk': {
      id: '/crosswalk'
      path: '/crosswalk'
      fullPath: '/crosswalk'
      preLoaderRoute: typeof CrosswalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$slug': {
      id: '/brief/$slug'
      path: '/brief/$slug'
      fullPath: '/brief/$slug'
      preLoaderRoute: typeof BriefSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest': {
      id: '/api/public/hooks/ingest'
      path: '/api/public/hooks/ingest'
      fullPath: '/api/public/hooks/ingest'
      preLoaderRoute: typeof ApiPublicHooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrosswalkRoute: CrosswalkRoute,
  GraphRoute: GraphRoute,
  RadarRoute: RadarRoute,
  StoreRoute: StoreRoute,
  BriefSlugRoute: BriefSlugRoute,
  ApiPublicHooksIngestRoute: ApiPublicHooksIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
